ProjectAlmond/ProjectAlmond.pro
ProjectAlmond/datum.cpp
ProjectAlmond/datum.h
ProjectAlmond/glavniprozor.cpp
ProjectAlmond/glavniprozor.h
ProjectAlmond/glavniprozor.ui
ProjectAlmond/unetiosobu.cpp
ProjectAlmond/unetiosobu.h
ProjectAlmond/unetiosobu.ui

ubacila sam toolbar sa slicicama na glavni prozor kao i prostor na kome
cemo izsrtavati stablo takodje sam u pro fajl dodala c++11

Izmenila sam greske u klasi datum napravila sam prozor za unosenje osobe

---

ProjectAlmond/glavniprozor.cpp
ProjectAlmond/glavniprozor.h

Malo sam sredila gui sad bolje radi.

Podesila sam da toolbutton malo bolje radi.

---

ProjectAlmond/glavniprozor.cpp
ProjectAlmond/glavniprozor.h
ProjectAlmond/unetiosobu.cpp
ProjectAlmond/unetiosobu.h

Podesila sam da se akcije desavaju kada se otpusti mis ostalo mi je da omogucim ispustanje na sceni i da podesim u klasi osoba prazan
konstruktor i konstruktor koji prima pol da bi mogli da pravimo osobu.

Podesavanja na GUI-ju

---

ProjectAlmond/glavniprozor.cpp
ProjectAlmond/glavniprozor.h
ProjectAlmond/unetiosobu.cpp
ProjectAlmond/unetiosobu.h

Dodala sam pod komentar stvari koje ce mi kasnije trebati i izbacila neke nepotrebne

Neke izmene na GUI-ju

---

ProjectAlmond/ProjectAlmond.pro
ProjectAlmond/alati/datum.cpp
ProjectAlmond/alati/datum.h
ProjectAlmond/engine/osoba.cpp
ProjectAlmond/engine/osoba.h
ProjectAlmond/engine/porodicnostablo.cpp
ProjectAlmond/engine/porodicnostablo.h
ProjectAlmond/engine/relacija.h
ProjectAlmond/engine/supruznik.cpp
ProjectAlmond/engine/supruznik.h

Dodao porodicno stablo, radicu na njemu i sutra i prekosutra, dodao jedan metod u klasu datum, kao i pojam sifre koja jedinstveno odredjuje datu osobu i datu relaciju.. Nista previse spektakularno i nista provereno za sada

Porodicno stablo

---

ProjectAlmond/engine/osoba.cpp
ProjectAlmond/engine/osoba.h
ProjectAlmond/engine/porodicnostablo.cpp
ProjectAlmond/engine/porodicnostablo.h
ProjectAlmond/engine/relacija.cpp
ProjectAlmond/engine/relacija.h

Tu su metodi za kreiranje stabla.
Kada se nova osoba crta na ekranu, sa prikupljenim podacima se poziva
DodajOsobu koja vraca sifru kreirane osobe, koja se dalje cuva u
objektu-widgetu za iscrtavanje.
Time stanje porodicnog stabla prelazi u nepovezano, sto se moze
proveriti pozivanjem metoda stabloJePovezano.
Pri kreiranju relacije izmedju dve osobe, engin-u se salju sifre te dve
osobe i tip relacije koju treba kreirati, koriscenjem metoda
PoveziOsobe, koji, osim sto povezuje date osobe, prebacuje i strukturu u
validno stanje, tj povezano, ako su povezane sve osobe koje su do tada
bile nepovezane.
U svakom momentu, moguce je pristupiti pokazivacu na kljucnu osobu
koriscenjem KljucnaOsoba, kao i na odredjenu osobu po njenoj sifri
koriscenjem nadjiOsobuPoSifri.

Dodao jos stvari u porodicnostablo.

---

ProjectAlmond/GUI/glavniprozor.cpp
ProjectAlmond/GUI/glavniprozor.h

Ostavila sam komentare za pravljenje widget-a i videla sam kako se pomera na odredjenu poziciju.

Pobrisala sam da se relacije ne prevlace i podesila slot za relaciju

---

ProjectAlmond/GUI/glavniprozor.cpp
ProjectAlmond/GUI/glavniprozor.h
ProjectAlmond/ProjectAlmond.pro
ProjectAlmond/widgetosoba.cpp
ProjectAlmond/widgetosoba.h
ProjectAlmond/widgetosoba.ui

Nije onako kako sam zamislila, ali za sad neka bude ovako, moram prvo prouciti neke stvari :)

WidgetOsoba (ne radi jos nista)

---

ProjectAlmond/engine/porodicnostablo.cpp
ProjectAlmond/engine/porodicnostablo.h

Dodao jos dva indeksa, koji indeksiraju osobe i relacije po sifri, da bih ubrzao proces pretrage po sifri, koji je zapravo i najcesca
operacija.

Dodavanje jos dva indeksa, radi brze pretrage

---

ProjectAlmond/engine/porodicnostablo.cpp
ProjectAlmond/engine/porodicnostablo.h

Dodao mogucnost brisanja osobe ili relacije na zahtev sa neke udaljene strane. Daj Boze da radi sve kako treba, posto ce uskoro on jedini i
znati kako radi.

Dodato brisanje

---

ProjectAlmond/GUI/glavniprozor.cpp
ProjectAlmond/GUI/glavniprozor.h
ProjectAlmond/glavniprozor.ui

... jako primitivno jos uvek :), u sustini vecinu stvari tek treba implementirati ali pise u komentarima
sta

E sad, pocela sam povezivanje GUI-a i engine-a

---

ProjectAlmond/GUI/glavniprozor.cpp
ProjectAlmond/GUI/glavniprozor.h
ProjectAlmond/widgetosoba.cpp
ProjectAlmond/widgetosoba.h

Dodavanje osobe jos ne radi ono sto treba, tj dodaje jednu koja je tu za test, 
treba dodati signal i slot za rucicu i ?, ali dugmici su dodati u toolbar (bez slicica)

Radimo dalje

---

ProjectAlmond/GUI/glavniprozor2.cpp
ProjectAlmond/GUI/glavniprozor2.h
ProjectAlmond/widgetosoba.cpp

mislim da je relativno ok, nastavljam sutra

dosta za danas

---

ProjectAlmond/GUI/glavniprozor.h
ProjectAlmond/GUI/glavniprozor2.cpp
ProjectAlmond/GUI/glavniprozor2.h
ProjectAlmond/GUI/widgetosoba.cpp
ProjectAlmond/GUI/widgetosoba.h

ne radi kako treba, ali da se srediti

pocela sam da radim na povezivanju osoba, nastavicu kasnije

---

ProjectAlmond/GUI/dialognovaosoba.cpp
ProjectAlmond/GUI/dialognovaosoba.h
ProjectAlmond/GUI/glavniprozor2.cpp
ProjectAlmond/GUI/glavniprozor2.h
ProjectAlmond/GUI/widgetosoba.cpp
ProjectAlmond/GUI/widgetosoba.h

Dodala sam signale malo se igrala sa css-om obrisala sve sto se dinamicki alocira u destruktoru podesila sam da se na signal toggled
uklanja osoba ali da bi to radilo moram da podesim set checkable true
ali kad to podesim kako god da kliknem na dugme ceo prozor mi nestane
ostavila sam da ga jos podesimo posle

Neka podesavanja Aida nastavlja

---

ProjectAlmond/GUI/glavniprozor2.cpp
ProjectAlmond/GUI/glavniprozor2.h
ProjectAlmond/GUI/widgetosoba.cpp
ProjectAlmond/GUI/widgetosoba.h

Samo sam zakomentarisala neke stvari, neke od njih su uzrokovale da ne radi kako treba, sad se cini ok. Treba videti u cemu je bio problem...

uklonjen crash

---

ProjectAlmond/GUI/glavniprozor2.cpp
ProjectAlmond/GUI/glavniprozor2.h
ProjectAlmond/GUI/widgetosoba.cpp
ProjectAlmond/GUI/widgetosoba.h

kao radi, ali opet ovako:
klik tip_relacije
klik prva
klik druga
videcu da promenim to ipak na ono sto smo inicijalno hteli

Povezivanje osoba (ne i komunkacija sa engine-om)

---

ProjectAlmond/GUI/glavniprozor2.cpp
ProjectAlmond/GUI/glavniprozor2.h
ProjectAlmond/GUI/widgetosoba.cpp
ProjectAlmond/ProjectAlmond.pro
ProjectAlmond/alati/filterobject.cpp
ProjectAlmond/alati/filterobject.h

Kako da nam razliciti widget-i isto reaguju na mousepressed i released, sto bi mozda moglo bilo korisno.
U svakom slucaju, samo sam dodala 2 nova fajla koji nimalo ne uticu na ono sto je vec uradjeno.

Jedna ideja

---

ProjectAlmond/GUI/glavniprozor2.cpp
ProjectAlmond/slike.qrc

Sada radi, uz upozorenje, trebace mu dugo da se bilduje prvi put, zbog

---

ProjectAlmond/GUI/glavniprozor2.cpp
ProjectAlmond/GUI/glavniprozor2.h
ProjectAlmond/GUI/widgetosoba.cpp
ProjectAlmond/GUI/widgetosoba.h
ProjectAlmond/engine/osoba.cpp
ProjectAlmond/engine/porodicnostablo.cpp
ProjectAlmond/widgetosoba.ui

Napravio povezivanje dve osobe, za sada deluje da engine ne pravi problem.
Moracu sutra da precistim kod ujutru, pre nego sto neko drugi krene da
ga koristi, da bih stvari nazvao pravim imenom.
Odusevljeno sam saznao da mi ipak treba drag and drop, posto u momentu
kada jedan widget uzme mousepressed on drzi i misa i samo on moze da
prihvati mouse released. Glup jezik

Radi povezivanje dve osobe, potrebno jos sredjivanja pre nego sto mozete nastaviti

---

ProjectAlmond/GUI/glavniprozor2.cpp
ProjectAlmond/GUI/glavniprozor2.h
ProjectAlmond/GUI/okvirstabla.cpp
ProjectAlmond/GUI/okvirstabla.h
ProjectAlmond/alati/filterobject.cpp
ProjectAlmond/alati/filterobject.h

To se prosledjuje okviru za crtanje stabla.
Ako bi nasi widgeti za osobu i relaciju imali to, mislim da bi radilo
sve kako treba, testirala sam na jednom obicnom dugmetu (pogledajte
konstruktor za glavni prozor), i pogledajte kako radi. 
Treba  sad izmeniti osobu, kao i sam filter da radi tacno ono sto nam je potrebno.

Dodala filter koji implementira MousePressed i Released

---

ProjectAlmond/alati/filterobject.cpp
ProjectAlmond/alati/filterobject.h

Ostaje da treba implementirati sve do kraja.

Popravljen problem, mislim da je sada u redu.

---

ProjectAlmond/GUI/glavniprozor2.cpp
ProjectAlmond/GUI/glavniprozor2.h
ProjectAlmond/GUI/okvirstabla.cpp
ProjectAlmond/GUI/okvirstabla.h
ProjectAlmond/alati/filterobject.cpp

Za sad kliktanje po tool baru samo ispisuje sta treba da se radi. Pomeranje osobe isto kako treba.
Bice dovrseno sutra, sigurno.

Nijedan warning :)

---

ProjectAlmond/GUI/glavniprozor2.cpp
ProjectAlmond/GUI/glavniprozor2.h
ProjectAlmond/GUI/okvirstabla.cpp
ProjectAlmond/GUI/widgetosoba.cpp
ProjectAlmond/GUI/widgetosoba.h
ProjectAlmond/alati/filterobject.cpp

ali ne svidja mi se bas ovakvo resenje.

Malo jos popravljeno,

---

ProjectAlmond/alati/datum.cpp
ProjectAlmond/alati/datum.h

Popodne radim i za sve ostale klase, da bi vas sacekalo spremno za
cuvanje u fajl :)

Dodao toString u datum i sredio upis i ispis u fajl za datum.

---

ProjectAlmond/GUI/glavniprozor2.cpp
ProjectAlmond/GUI/glavniprozor2.h
ProjectAlmond/GUI/okvirstabla.cpp
ProjectAlmond/GUI/okvirstabla.h
ProjectAlmond/GUI/widgetosoba.cpp
ProjectAlmond/GUI/widgetosoba.h
ProjectAlmond/GUI/widgetrelacija.cpp
ProjectAlmond/GUI/widgetrelacija.h
ProjectAlmond/ProjectAlmond.pro
ProjectAlmond/alati/linija.cpp
ProjectAlmond/alati/linija.h
ProjectAlmond/widgetrelacija.ui

Od sutra prelazim na engine, da sredim probleme i dodam nove neophodne
stvari :)

Dodao neke rudimentarne prikaze relacija, bice jos dosta posla.

---

ProjectAlmond/GUI/dialognovaosoba.cpp
ProjectAlmond/GUI/dialognovaosoba.h
ProjectAlmond/GUI/glavniprozor2.cpp
ProjectAlmond/dialognovaosoba.ui

Dodata opcija neunosenja podataka u dijalogu pri kreiranju nove osobe,i promenjeno je znacenje checkbox-ova u istom.

Izmene dijaloga za novu osobu

---

ProjectAlmond/engine/brak.cpp
ProjectAlmond/engine/brak.h
ProjectAlmond/engine/osoba.cpp
ProjectAlmond/engine/osoba.h
ProjectAlmond/engine/porodicnostablo.cpp
ProjectAlmond/engine/porodicnostablo.h

Dovrsen osnovni skup funkcionalnosti engina, za dodavanje i brisanje clanova

---

ProjectAlmond/GUI/glavniprozor.cpp
ProjectAlmond/GUI/glavniprozor.h
ProjectAlmond/GUI/okvirstabla.cpp
ProjectAlmond/engine/brak.cpp
ProjectAlmond/engine/brak.h
ProjectAlmond/engine/dete.cpp
ProjectAlmond/engine/dete.h
ProjectAlmond/engine/osoba.cpp
ProjectAlmond/engine/osoba.h
ProjectAlmond/engine/porodicnostablo.cpp
ProjectAlmond/engine/porodicnostablo.h

Dobro i dodaje i brise osobe i relaciju supruznik, problem je sto se
lose vidi brisanje na panelu, kao i to sto sam datume ubio zbog problema
sa QDate. Sutra ide ovako za prezentaciju, a od 2 do 6 cu srediti datum
i ostalo do kraja, tako da mozete da nastavite sredjivanje GUI :)

Napravio sam ga da tek da radi za sutra.

---

ProjectAlmond/GUI/dialognovaosoba.cpp
ProjectAlmond/GUI/dialognovaosoba.h
ProjectAlmond/GUI/glavniprozor.cpp
ProjectAlmond/dialognovaosoba.ui
ProjectAlmond/engine/porodicnostablo.h

Ne puca vise kada sa klikne na odustani(pre se svejedno pravila
relacija).
Dodala sam i jedan komentar u prodicnostablo.h, mislim da nam to nije problem da uradimo.

Dijalogu za kreiranje osobe dodat unos trivije.

---

ProjectAlmond/GUI/dialognovaosoba.cpp
ProjectAlmond/GUI/dialognovaosoba.h
ProjectAlmond/GUI/glavniprozor.cpp
ProjectAlmond/GUI/glavniprozor.h
ProjectAlmond/glavniprozor.ui
ProjectAlmond/main.cpp

otvaranje vise prozora, poruke.

Jos neke akcije glavnog menija,

---

ProjectAlmond/GUI/dijalogizmenaosobe.cpp
ProjectAlmond/GUI/dijalogizmenaosobe.h
ProjectAlmond/GUI/dijalogizmenaosobe.ui
ProjectAlmond/GUI/glavniprozor.cpp
ProjectAlmond/GUI/glavniprozor.h
ProjectAlmond/ProjectAlmond.pro

Malo izmena u glavniprozor.cpp.

Dodat DijalogIzmenaOsobe.

---

ProjectAlmond/GUI/glavniprozor.cpp
ProjectAlmond/GUI/glavniprozor.h
ProjectAlmond/GUI/okvirstabla.cpp
ProjectAlmond/GUI/okvirstabla.h

Male popravke u dodavanju novog deteta.

---

ProjectAlmond/GUI/glavniprozor.cpp
ProjectAlmond/GUI/glavniprozor.h

Read&Write settings

---

ProjectAlmond/GUI/glavniprozor.cpp
ProjectAlmond/GUI/glavniprozor.h
ProjectAlmond/glavniprozor.ui

kao i dodavanje skoro otvaranih fajlova na pravo mesto

Sredio sam pojavljivanje dokova u zavisnosti od cekiranosti onih polja,

---

ProjectAlmond/engine/osoba.cpp
ProjectAlmond/engine/osoba.h
ProjectAlmond/engine/porodicnostablo.cpp

Samo sam dodao deo ucitavanja i upisa podataka koji se ticu pojedinacne osobe, bez vezivanja

Pocetak upisa i ispisa

---

ProjectAlmond/engine/brak.cpp
ProjectAlmond/engine/brak.h
ProjectAlmond/engine/dete.cpp
ProjectAlmond/engine/dete.h
ProjectAlmond/engine/porodicnostablo.cpp

Dodao ispis u fajl, sutra ujutru dodajem citanje iz istog i rekonstrukciju podataka.
Moram da primetim da filteri ne rade bas najbolje, tj ne prikazuje mi
vec postojece fajlove, a valjalo bi da onaj FileChooser, ili kako god da
se zove, da pamti gde je poslednji put otvaran...
Vidimo se sutra :D

Ispis u fajl, citanje sutra ujutru

---

ProjectAlmond/GUI/glavniprozor.cpp
ProjectAlmond/GUI/glavniprozor.h

Dodala sam za jezik da stalno bude cekirano jedno. Ostavila sam da se dorade rucne stvari.

Dorade na jeziku

---

ProjectAlmond/GUI/glavniprozor.cpp
ProjectAlmond/GUI/glavniprozor.h
ProjectAlmond/GUI/gosoba.cpp
ProjectAlmond/GUI/gosoba.h
ProjectAlmond/GUI/stablo.cpp
ProjectAlmond/ProjectAlmond.pro

Za sada, iscrtava samo neke pravougaonike dok ne napravim ajteme za
osobe i relacije koji ce se ponasati kako treba. Posle ce se pozivati
odgovarajuci dijalozi i metodi koje vec imamo prakticno.
PS. zaista ne razumem kako da uradim itemAt za scenu, trazi mi transform a onda se buni je nesto privatno... Kada to shvatim, ostatak nece biti problem :D

Povezala sam scenu i pogled sa toolbarom, donekle.

---

ProjectAlmond/GUI/glavniprozor.cpp

Ostalo je jos da se naprave klase koje nasledjuju GraphicItem za osobe i relacije.

Sredjen problem sa itemAt

---

ProjectAlmond/engine/brak.cpp
ProjectAlmond/engine/brak.h
ProjectAlmond/engine/dete.cpp
ProjectAlmond/engine/dete.h
ProjectAlmond/engine/osoba.cpp
ProjectAlmond/engine/osoba.h
ProjectAlmond/engine/porodicnostablo.cpp

Zavrsio ucitavanje iz fajlova, jos samo da ucinim da zapravo radi kako treba :P
Za sada nemojte da ga koristite XD

Nastavak rada na fajlovima

---

ProjectAlmond/GUI/glavniprozor.cpp
ProjectAlmond/GUI/glavniprozor.h
ProjectAlmond/GUI/gosoba.cpp
ProjectAlmond/GUI/gosoba.h
ProjectAlmond/GUI/okvirstabla.cpp
ProjectAlmond/GUI/okvirstabla.h
ProjectAlmond/GUI/widgetosoba.cpp
ProjectAlmond/GUI/widgetosoba.h
ProjectAlmond/GUI/widgetrelacija.cpp
ProjectAlmond/GUI/widgetrelacija.h
ProjectAlmond/alati/filterobject.cpp
ProjectAlmond/alati/filterobject.h

Povezala sam ga sa vecinom funkcija.
I izbacila sam neke delove koje vise necemo koristiti.

Nastavak rada na GraphicItem-u za osobu.

---

ProjectAlmond/engine/brak.cpp
ProjectAlmond/engine/brak.h
ProjectAlmond/engine/dete.cpp
ProjectAlmond/engine/dete.h
ProjectAlmond/engine/osoba.cpp
ProjectAlmond/engine/osoba.h
ProjectAlmond/engine/porodicnostablo.cpp

sada moj deo vise ne puca. Treba da sredim nesto u vezi sa brisanjem,
ali necete taj problem osetiti jos uvek, tako da cu to popodne :)

Bez podrske GUI-a, tesko mi je da izvalim da li je sve u redu, ali za

---

ProjectAlmond/engine/brak.cpp
ProjectAlmond/engine/dete.cpp
ProjectAlmond/engine/osoba.cpp

Sada ne bi trebalo da bude problema pri brisanju bilo cega, cekam na zavrsetak GUI-a, da bih testirao cuvanje.
U medjuvremenu cu obezbediti metod koji po sifri vraca stepen srodstva u odnosu na koren.

Sredjeno brisanje, cekam kraj GUI-a za nastavak

---

ProjectAlmond/GUI/dialognovaosoba.cpp
ProjectAlmond/GUI/dialognovaosoba.h
ProjectAlmond/GUI/dijalogrelacija.h
ProjectAlmond/GUI/glavniprozor.cpp
ProjectAlmond/GUI/glavniprozor.h
ProjectAlmond/GUI/gosoba.cpp
ProjectAlmond/GUI/gosoba.h
ProjectAlmond/GUI/grelacija.cpp
ProjectAlmond/GUI/stablo.cpp

Dodavanje, iscrtavanje, pomeranje.

GUI izmene

---

ProjectAlmond/GUI/dialognovaosoba.cpp
ProjectAlmond/GUI/dialognovaosoba.h
ProjectAlmond/GUI/dijalogizmenaosobe.cpp
ProjectAlmond/GUI/dijalogizmenaosobe.h
ProjectAlmond/GUI/dijalogrelacija.cpp
ProjectAlmond/GUI/dijalogrelacija.h
ProjectAlmond/GUI/glavniprozor.cpp
ProjectAlmond/GUI/glavniprozor.h
ProjectAlmond/ProjectAlmond.pro
ProjectAlmond/jezici.qrc

Sredila sam prevod, jos samo u glavnom prozoru izmena.
Treba jos da namestim da moze da se vrati na srpski.

Dorada jezika

---

ProjectAlmond/GUI/glavniprozor.cpp
ProjectAlmond/engine/brak.cpp
ProjectAlmond/engine/dete.cpp
ProjectAlmond/engine/osoba.cpp
ProjectAlmond/engine/porodicnostablo.cpp

Treba da se doradi jos uvek ne radi kako treba.

Ispis i upis

---

ProjectAlmond/GUI/glavniprozor.cpp
ProjectAlmond/engine/osoba.cpp
ProjectAlmond/engine/osoba.h
ProjectAlmond/engine/porodicnostablo.cpp
ProjectAlmond/engine/porodicnostablo.h

Pisanje u fajl je radilo, ali sad je proradilo i citanje, ali nisam ga zavrsila, za sad uradjen samo deo za kljucnu osobu.

Ispis u fajl

---

ProjectAlmond/GUI/dijalogizmenaosobe.cpp
ProjectAlmond/GUI/dijalogizmenaosobe.h
ProjectAlmond/GUI/glavniprozor.cpp
ProjectAlmond/GUI/glavniprozor.h
ProjectAlmond/engine/brak.cpp
ProjectAlmond/engine/dete.cpp
ProjectAlmond/engine/osoba.cpp
ProjectAlmond/engine/porodicnostablo.cpp
ProjectAlmond/engine/porodicnostablo.h
ProjectAlmond/glavniprozor.ui

Vracam se na GUI, da ga povezem sa ovim

IndeksRodjendan, mala popravka u citanju

---

ProjectAlmond/ProjectAlmond.pro
ProjectAlmond/alati/trazenjeputa.cpp
ProjectAlmond/alati/trazenjeputa.h
ProjectAlmond/engine/porodicnostablo.cpp
ProjectAlmond/engine/porodicnostablo.h

...Ali moram da vidim kako sada da se koristim engine-om i multimapama za pretragu, pre nego sto nastavim :)

Poceo sam da dodajem metode za pretragu.

---

ProjectAlmond/alati/trazenjeputa.cpp
ProjectAlmond/alati/trazenjeputa.h
ProjectAlmond/engine/porodicnostablo.cpp
ProjectAlmond/engine/porodicnostablo.h

Dodao jos dva gettera koja mi trebajju

Samo da sacuvam pocetak, da ne moram da pisem ispocetka.

---

ProjectAlmond/alati/trazenjeputa.cpp
ProjectAlmond/alati/trazenjeputa.h
ProjectAlmond/engine/porodicnostablo.cpp
ProjectAlmond/engine/porodicnostablo.h

omoguceno trazenje puta od osobe do osobe, vracanjem vektora sa siframa na putu

dodato trazenje puta

---

ProjectAlmond/GUI/dialognovaosoba.cpp
ProjectAlmond/GUI/dialogpretrage.cpp
ProjectAlmond/GUI/dialogpretrage.h
ProjectAlmond/GUI/dialogpretrage.ui
ProjectAlmond/GUI/dijalogizmenaosobe.cpp
ProjectAlmond/GUI/dijalogpretrage.cpp
ProjectAlmond/GUI/dijalogpretrage.h
ProjectAlmond/GUI/dijalogpretrage.ui
ProjectAlmond/GUI/dijalogrelacija.cpp
ProjectAlmond/GUI/glavniprozor.cpp
ProjectAlmond/GUI/glavniprozor.h
ProjectAlmond/GUI/glavniprozor.ui
ProjectAlmond/ProjectAlmond.pro

Za datum rodjenja vec ima (komeJeRodjendan(datum)), za ostale podatke uraditi slicno...

Popravljena pretraga, napraviti enum i odgovarajuce funkcije u stablu.

---

ProjectAlmond/GUI/glavniprozor.cpp
ProjectAlmond/GUI/glavniprozor.h
ProjectAlmond/engine/osoba.cpp
ProjectAlmond/engine/osoba.h

Ali posto moram da idem, neka ovoga za sad

Samo pocetak povezivanja GUI sa citanjem iz fajla

---

ProjectAlmond/alati/trazenjeputa.cpp
ProjectAlmond/engine/porodicnostablo.cpp
ProjectAlmond/engine/porodicnostablo.h

nastavak rada na utvrdjivanju srodstva, dodat jedan metod u

---

ProjectAlmond/GUI/glavniprozor.cpp
ProjectAlmond/GUI/glavniprozor.h
ProjectAlmond/GUI/grelacija.cpp
ProjectAlmond/GUI/grelacija.h
ProjectAlmond/engine/brak.cpp
ProjectAlmond/engine/osoba.cpp
ProjectAlmond/engine/porodicnostablo.cpp
ProjectAlmond/engine/porodicnostablo.h

Ucitavanje, n!-ti put

---

ProjectAlmond/GUI/glavniprozor.cpp
ProjectAlmond/GUI/glavniprozor.h
ProjectAlmond/engine/osoba.cpp
ProjectAlmond/engine/porodicnostablo.cpp
ProjectAlmond/engine/porodicnostablo.h

da imamo opciju dodavanja korene osobe, sad trazim gde nastaje problem
sa ovim

Pocela sam da radim na tome da se na pocetku ne pravi Pera Detlic, vec

---

ProjectAlmond/GUI/glavniprozor.cpp
ProjectAlmond/GUI/glavniprozor.ui
ProjectAlmond/engine/porodicnostablo.cpp
ProjectAlmond/engine/porodicnostablo.h

moze da se snimi, ali treba izmeniti citanje iz fajla tako da radi i u
tom slucaju

Pogledajte da li je ovo ok, i ima jedan problem, ako je stablo prazno

---

ProjectAlmond/GUI/glavniprozor.cpp
ProjectAlmond/alati/trazenjeputa.cpp
ProjectAlmond/alati/trazenjeputa.h
ProjectAlmond/engine/porodicnostablo.cpp
ProjectAlmond/engine/porodicnostablo.h

Sredio sam, tako da deluje da radi korektno, sada treba podrzati GUI-em
